In [1]:
 import numpy as np  
i = np.array(10)  #oD
print(i)

10


In [2]:
 import numpy as np
i = np.array([10, 20, 30, 40, 50])  #1D
print(i)

[10 20 30 40 50]


In [3]:
import numpy as np   #2D
p = np.array([
[15, 20, 35],
[45, 55, 60]
])
print(p)

[[15 20 35]
 [45 55 60]]


In [5]:
import numpy as np    #3D
p = np.array([
[[15, 25, 35], [45, 55, 65]],
[[10, 20, 30], [40, 50, 60]]
])
print(p)

[[[15 25 35]
  [45 55 65]]

 [[10 20 30]
  [40 50 60]]]


In [6]:
import numpy as np
i = np.array(10)
j = np.array([10, 20, 30, 40, 50])
k = np.array([[11, 22, 33], [44, 55, 66]])
m = np.array([[[10, 20, 30], [40, 50, 60]], [[10, 20, 30], [40, 50, 
60]]])
print(i.ndim)
print(j.ndim)
print(k.ndim)
print(m.ndim)

0
1
2
3


In [7]:
import numpy as np
i = np.array([10, 20, 30, 40], ndmin=5)
print(i)
print(i.ndim)

[[[[[10 20 30 40]]]]]
5
